package com.lz_insurance.insurance.identity.domain.dto;

/**
 * Input for the tenant bootstrap ceremony (UJ-001). A domain-owned record: no validation
 * annotations here — structural request validation is the DTO layer's job; the business rules
 * (password policy, idempotency, invariants) are enforced inside the use case.
 *
 * <p>Bootstrap now CREATES the tenant, its headquarter branch and the first admin atomically, so the
 * caller supplies the tenant/branch details rather than pre-existing ids. {@code tenantCode} is the
 * unique idempotency key; the server generates tenantId / branchId / identityProfileId. The temporary
 * password is generated by OUR system (never supplied here) and delivered out-of-band.
 *
 * @param tenantName     display name of the new tenant
 * @param tenantCode     unique tenant slug — the idempotency key
 * @param country        ISO 3166-1 alpha-2 country code
 * @param hqBranchName   display name of the headquarter branch
 * @param hqBranchCode   headquarter branch code (unique within the tenant)
 * @param adminEmail     first TENANT_ADMIN's email (also the Keycloak username)
 * @param adminFirstName admin first name
 * @param adminLastName  admin last name
 */
public record CreateAdminTenantRequest(
        String tenantName,
        String tenantCode,
        String country,
        String hqBranchName,
        String hqBranchCode,
        String adminEmail,
        String adminFirstName,
        String adminLastName) {
}
