package com.lz_insurance.insurance.identity.infrastructure.persistence.adapter;

import com.lz_insurance.insurance.identity.domain.model.Branch;
import com.lz_insurance.insurance.identity.infrastructure.persistence.entity.BranchEntity;
import org.mapstruct.Mapper;

/**
 * Maps {@link Branch} &harr; {@link BranchEntity}.
 * Domain&rarr;Entity is generated by MapStruct; Entity&rarr;Domain rebuilds through
 * {@code Branch.reconstitute(...)} (which keeps the HQ-no-parent structural rule).
 */
@Mapper(componentModel = "spring")
public interface BranchPersistenceMapper extends BaseFieldsMapper {

    BranchEntity toEntity(Branch domain);

    default Branch toDomain(BranchEntity entity) {
        if (entity == null) {
            return null;
        }
        Branch domain = Branch.reconstitute(
                entity.getTenantId(),
                entity.getParentBranchId(),
                entity.getName(),
                entity.getCode(),
                entity.getType(),
                entity.getStatus());
        applyBaseFields(entity, domain);
        return domain;
    }
}
