package com.lz_insurance.insurance.identity.infrastructure.persistence.adapter;

import com.lz_insurance.insurance.identity.domain.model.Tenant;
import com.lz_insurance.insurance.identity.infrastructure.persistence.entity.TenantEntity;
import org.mapstruct.Mapper;

/**
 * Maps {@link Tenant} &harr; {@link TenantEntity}.
 * Domain&rarr;Entity is generated by MapStruct (by-name, including base fields).
 * Entity&rarr;Domain rebuilds through {@code Tenant.reconstitute(...)} then restores base fields.
 */
@Mapper(componentModel = "spring")
public interface TenantPersistenceMapper extends BaseFieldsMapper {

    TenantEntity toEntity(Tenant domain);

    default Tenant toDomain(TenantEntity entity) {
        if (entity == null) {
            return null;
        }
        Tenant domain = Tenant.reconstitute(
                entity.getName(),
                entity.getCode(),
                entity.getCountry(),
                entity.isBootstrapped(),
                entity.getHeadquarterBranchId(),
                entity.getStatus());
        applyBaseFields(entity, domain);
        return domain;
    }
}
