<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.lz_Insurance</groupId>
        <artifactId>lz_insurance</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>insurance-identity-service</artifactId>
    <packaging>pom</packaging>

    <properties>
        <maven.compiler.source>25</maven.compiler.source>
        <maven.compiler.target>25</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <modules>
        <module>insurance-identity-infrastructure</module>
        <module>insurance-identity-api</module>
        <module>insurance-identity-domain</module>
    </modules>

</project>