package com.lz_insurance.insurance.identity.domain.usecase;

import com.lz_insurance.core.context.RequestContext;
import com.lz_insurance.core.exception.ErrorCode;
import com.lz_insurance.core.exception.InsuranceException;
import com.lz_insurance.insurance.identity.domain.dto.BootstrapResult;
import com.lz_insurance.insurance.identity.domain.dto.CreateAdminTenantRequest;
import com.lz_insurance.insurance.identity.domain.dto.KeycloakUserRegistration;
import com.lz_insurance.insurance.identity.domain.enums.BranchType;
import com.lz_insurance.insurance.identity.domain.enums.InternalUserType;
import com.lz_insurance.insurance.identity.domain.model.Branch;
import com.lz_insurance.insurance.identity.domain.model.IdentityProfile;
import com.lz_insurance.insurance.identity.domain.model.Tenant;
import com.lz_insurance.insurance.identity.domain.port.in.BootstrapTenantPort;
import com.lz_insurance.insurance.identity.domain.port.out.BranchRepository;
import com.lz_insurance.insurance.identity.domain.port.out.IdentityProfileRepository;
import com.lz_insurance.insurance.identity.domain.port.out.KeycloakUserPort;
import com.lz_insurance.insurance.identity.domain.port.out.PasswordHasher;
import com.lz_insurance.insurance.identity.domain.port.out.TenantRepository;
import com.lz_insurance.insurance.identity.domain.support.PasswordPolicy;
import lombok.extern.slf4j.Slf4j;

/**
 * Tenant bootstrap ceremony (US-M2-002 / UJ-001). Framework-free: constructed with its out-ports by
 * {@code IdentityUseCaseConfig}. Atomically stands up a brand-new tenant: {@code Tenant} + headquarter
 * {@code Branch} + first {@code TENANT_ADMIN} — a tenant without an HQ branch and an admin is an
 * incomplete, unusable state.
 *
 * <p><b>Idempotency</b> keys on {@code tenantCode}: already-bootstrapped → 409; a code that exists but
 * is NOT bootstrapped signals a partial/failed prior attempt → 409 for ops review (never a silent
 * resume).
 *
 * <p><b>DB-first, Keycloak-compensated</b> ordering: the DB aggregates are created first, then the
 * Keycloak account; if a Keycloak step fails the DB records (and any created Keycloak user) are
 * removed so a retry starts clean. The temporary password is generated by OUR system, sent raw to
 * Keycloak, and stored ONLY as a BCrypt hash on the profile — our authoritative copy for the later
 * forced-change verification (Keycloak never rejects on policy; see {@code docs/user-journeys.md}).
 */
@Slf4j
public class BootstrapTenantPortImpl implements BootstrapTenantPort {

    private static final String TENANT_ADMIN_ROLE = "TENANT_ADMIN";

    private final TenantRepository tenantRepository;
    private final BranchRepository branchRepository;
    private final IdentityProfileRepository identityProfileRepository;
    private final KeycloakUserPort keycloakUserPort;
    private final PasswordHasher passwordHasher;

    public BootstrapTenantPortImpl(TenantRepository tenantRepository,
                                   BranchRepository branchRepository,
                                   IdentityProfileRepository identityProfileRepository,
                                   KeycloakUserPort keycloakUserPort,
                                   PasswordHasher passwordHasher) {
        this.tenantRepository = tenantRepository;
        this.branchRepository = branchRepository;
        this.identityProfileRepository = identityProfileRepository;
        this.keycloakUserPort = keycloakUserPort;
        this.passwordHasher = passwordHasher;
    }

    @Override
    public BootstrapResult createTenantAdmin(CreateAdminTenantRequest request, RequestContext context) {
        log.info("Tenant {} bootstrap initiated [correlationId={}]", request.tenantCode(), context.correlationId());

        guardNotAlreadyBootstrapped(request.tenantCode());
        BootstrapAggregates created = createAggregates(request);

        String temporaryPassword = PasswordPolicy.generateRandomPassword();
        String keycloakUserId = provisionKeycloakAccount(request, temporaryPassword, created);

        finalizeBootstrap(created, keycloakUserId, temporaryPassword);

        log.info("Tenant {} bootstrapped by {} — HQ branch {}, TENANT_ADMIN profile {} [correlationId={}]", created.tenant().getId(), context.resolvedActorId(), created.branch().getId(), created.admin().getId(), context.correlationId());

        return new BootstrapResult(created.tenant().getId(), created.branch().getId(), created.admin().getId(), keycloakUserId);
    }

    private void guardNotAlreadyBootstrapped(String tenantCode) {
        log.info("verifying if tenant already exists");
        tenantRepository.findByCode(tenantCode).ifPresent(existing -> {
            if (existing.isBootstrapped()) {
                throw new InsuranceException(ErrorCode.DUPLICATE_RESOURCE, "Tenant with code '%s' is already bootstrapped".formatted(tenantCode));
            }
            log.warn("Partial bootstrap detected for tenantCode {} — a previous attempt may have failed", tenantCode);
            throw new InsuranceException(ErrorCode.DUPLICATE_RESOURCE, "A partial bootstrap exists for tenant code '%s'; ops review required before retry".formatted(tenantCode));
        });
    }

    private BootstrapAggregates createAggregates(CreateAdminTenantRequest request) {
        log.info("create Tenant + HQ Branch + PENDING_APPROVAL admin profile");
        Tenant tenant = tenantRepository.save(new Tenant(request.tenantName(), request.tenantCode(), request.country()));
        Branch branch = branchRepository.save(new Branch(tenant.getId(), null, request.hqBranchName(), request.hqBranchCode(), BranchType.HEADQUARTER));
        IdentityProfile admin = identityProfileRepository.save(IdentityProfile.internal(tenant.getId(), branch.getId(), InternalUserType.TENANT_ADMIN, request.adminEmail(), request.adminFirstName(), request.adminLastName()));
        return new BootstrapAggregates(tenant, branch, admin);
    }

    private String provisionKeycloakAccount(CreateAdminTenantRequest request, String temporaryPassword, BootstrapAggregates created) {
        String keycloakUserId;
        try {
            keycloakUserId = keycloakUserPort.createUser(new KeycloakUserRegistration(
                    request.adminEmail(), request.adminEmail(), request.adminFirstName(), request.adminLastName(),
                    temporaryPassword, true, true));
        } catch (RuntimeException e) {
            compensate(created, null);
            throw e;
        }
        try {
            keycloakUserPort.assignRealmRole(keycloakUserId, TENANT_ADMIN_ROLE);
        } catch (RuntimeException e) {
            compensate(created, keycloakUserId);
            throw e;
        }
        return keycloakUserId;
    }

    private void finalizeBootstrap(BootstrapAggregates created, String keycloakUserId, String temporaryPassword) {
        IdentityProfile admin = created.admin();
        admin.activate(keycloakUserId);
        admin.updatePasswordHash(passwordHasher.encrypt(temporaryPassword));
        identityProfileRepository.save(admin);

        Tenant tenant = created.tenant();
        tenant.markBootstrapped(created.branch().getId());
        tenantRepository.save(tenant);
    }

    /**
     * Undo a failed ceremony: remove the Keycloak account (if created) and the Phase-1 DB records, so
     * a retry starts clean. Each removal is best-effort — a failure is logged at ERROR with the id so
     * ops can finish the cleanup manually; the original provider exception is what propagates.
     */
    private void compensate(BootstrapAggregates created, String keycloakUserId) {
        log.error("Bootstrap failed for tenant {} (code {}) after Phase 1 — compensating; manual cleanup may be required", created.tenant().getId(), created.tenant().getCode());
        if (keycloakUserId != null) {
            safeDelete(() -> keycloakUserPort.deleteUser(keycloakUserId), "Keycloak user " + keycloakUserId);
        }
        safeDelete(() -> identityProfileRepository.deleteById(created.admin().getId()),
                "identity profile " + created.admin().getId());
        safeDelete(() -> branchRepository.deleteById(created.branch().getId()),
                "branch " + created.branch().getId());
        safeDelete(() -> tenantRepository.deleteById(created.tenant().getId()),
                "tenant " + created.tenant().getId());
    }

    private void safeDelete(Runnable deletion, String what) {
        try {
            deletion.run();
        } catch (RuntimeException ex) {
            log.error("Compensation could not remove {} — manual cleanup required", what, ex);
        }
    }

    /** The Phase-1 aggregates, carried across the ceremony's phases. */
    private record BootstrapAggregates(Tenant tenant, Branch branch, IdentityProfile admin) {
    }
}
