package com.lz_insurance.insurance.identity.api.dto.request;

import com.lz_insurance.insurance.identity.domain.dto.CreateAdminTenantRequest;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;

/**
 * Request body for {@code POST /identity/bootstrap}. Structural validation only — the business rules
 * (idempotency, invariants) are enforced by the use case; the temporary password is generated by OUR
 * system and never supplied here. Bean Validation failures surface as HTTP 400 via
 * {@code GlobalControllerAdvice}.
 */
public record BootstrapRequest(
        @NotBlank(message = "tenantName is required") String tenantName,
        @NotBlank(message = "tenantCode is required") String tenantCode,
        @NotBlank(message = "country is required")
        @Size(min = 2, max = 2, message = "country must be an ISO 3166-1 alpha-2 code") String country,
        @NotBlank(message = "hqBranchName is required") String hqBranchName,
        @NotBlank(message = "hqBranchCode is required") String hqBranchCode,
        @NotBlank(message = "adminEmail is required")
        @Email(message = "adminEmail must be a valid email") String adminEmail,
        @NotBlank(message = "adminFirstName is required") String adminFirstName,
        @NotBlank(message = "adminLastName is required") String adminLastName) {

    public static CreateAdminTenantRequest toDomain(BootstrapRequest request) {
        return new CreateAdminTenantRequest(
                request.tenantName(),
                request.tenantCode(),
                request.country(),
                request.hqBranchName(),
                request.hqBranchCode(),
                request.adminEmail(),
                request.adminFirstName(),
                request.adminLastName());
    }
}
